<a href="https://colab.research.google.com/github/Gadha-Viswanath/Regression-Techniques/blob/main/Regression_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1.Loading and preprocessing

In [ ]:
import pandas as pd
import numpy as np
from sklearn.datasets import fetch_california_housing
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

#loading the dataset and converting into pd dataframe
data = fetch_california_housing()
X = pd.DataFrame(data.data,columns=data.feature_names)
X
y = pd.Series(data.target, name='target')

In [ ]:
# Checking for missing values
missing = X.isnull().sum()
missing

MedInc        0
HouseAge      0
AveRooms      0
AveBedrms     0
Population    0
AveOccup      0
Latitude      0
Longitude     0
dtype: int64

No missing values in the dataset

In [ ]:
#lets standardize the features using StandardScalar
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled

array([[ 2.34476576,  0.98214266,  0.62855945, ..., -0.04959654,
         1.05254828, -1.32783522],
       [ 2.33223796, -0.60701891,  0.32704136, ..., -0.09251223,
         1.04318455, -1.32284391],
       [ 1.7826994 ,  1.85618152,  1.15562047, ..., -0.02584253,
         1.03850269, -1.33282653],
       ...,
       [-1.14259331, -0.92485123, -0.09031802, ..., -0.0717345 ,
         1.77823747, -0.8237132 ],
       [-1.05458292, -0.84539315, -0.04021111, ..., -0.09122515,
         1.77823747, -0.87362627],
       [-0.78012947, -1.00430931, -0.07044252, ..., -0.04368215,
         1.75014627, -0.83369581]])

Explanation of Preprocessing:

Missing Values: If there are missing values, it’s important to handle them to ensure that the model is not biased or inefficient due to incomplete data. In this dataset no missing values are there.

Feature Scaling: Standardizing the features ensures that all features are on a similar scale, preventing models from being biased toward features with larger scales. Standardization helps gradient-based algorithms converge faster and improves model accuracy.

In [ ]:
#Lets split the data into training and testing sets.
X_train,X_test,y_train,y_test = train_test_split(X_scaled,y,test_size=0.2,random_state=40)

# 2.Regression Algorithm Implementation

i)Linear Regression

In [ ]:
#importing necessary models
from sklearn.linear_model import LinearRegression

In [ ]:
#Initializing and fit the linear regression model
linear_reg = LinearRegression()
linear_reg.fit(X_train,y_train)

LinearRegression()

In [ ]:
#MAking predictions
linear_pred = linear_reg.predict(X_test)
linear_pred

array([2.00412998, 2.57561917, 1.19769801, ..., 2.42460902, 1.73085934,
       1.35765516])

Explanation:

Linear Regression assumes a linear relationship between the features and the target variable. If the relationship between features and target is roughly linear, this model will perform well.

The California Housing dataset includes features like income, house age, and average rooms, which might have linear relationships with the target variable, so starting with linear regression is a good choice.

ii)Decision Tree Regression

In [ ]:
#importing necessary models
from sklearn.tree import DecisionTreeRegressor

In [ ]:
#Initializing Decision tree regression
dt_reg = DecisionTreeRegressor()
dt_reg.fit(X_train,y_train)

DecisionTreeRegressor()

In [ ]:
#Making predictions
dt_pred = dt_reg.predict(X_test)
dt_pred

array([1.607, 2.294, 0.792, ..., 1.932, 2.335, 0.878])

Explanation:

A Decision Tree Regressor creates a tree-like structure by splitting the data at each node based on the best feature that reduces the variance within the split. This process continues until the data is split into smaller, homogenous groups (leaf nodes). Each leaf node provides a prediction by averaging the target values of the instances in that node.

Since the California Housing dataset may contain non-linear relationships between features and the target, Decision Trees can model such interactions.

iii)Random Forest Regression

In [ ]:
#importing necessary models
from sklearn.ensemble import RandomForestRegressor

In [ ]:
#Initializing Random forest regression
rf_reg = RandomForestRegressor()
rf_reg.fit(X_train,y_train)

RandomForestRegressor()

In [ ]:
#Making predictions
rf_pred = rf_reg.predict(X_test)
rf_pred

array([1.90154, 2.29724, 0.73605, ..., 1.9425 , 1.99646, 1.01543])

Explanation:

Random Forest is an ensemble learning method that creates multiple decision trees and aggregates their predictions. The final prediction is the average of all the trees' predictions, which helps to reduce overfitting and improve generalization.

Random Forest can model complex non-linear relationships It works well on high-dimensional datasets, like the California Housing dataset, where many features may interact with each other.

iv)Gradient boosting Regression

In [ ]:
#importing necessary models
from sklearn.ensemble import GradientBoostingRegressor

In [ ]:
#Initializing Gradient Boosting regression
gb_reg = GradientBoostingRegressor()
gb_reg.fit(X_train,y_train)

GradientBoostingRegressor()

In [ ]:
#Making predictions
gb_pred = gb_reg.predict(X_test)
gb_pred

array([1.81656876, 2.30660447, 0.8132348 , ..., 2.11724067, 2.03201091,
       0.91179624])

Explanation:

Gradient Boosting builds models sequentially. Each new model attempts to correct the residual errors of the previous model

Gradient Boosting is highly effective for datasets with complex, non-linear relationships. In the case of California Housing, it can model the non-linear effects of features on house prices.

v)Support Vector Regression (SVR)

In [ ]:
#importing necessary models
from sklearn.svm import SVR

In [ ]:
#Initializing Gradient Boosting regression
svr_reg = SVR()
svr_reg.fit(X_train,y_train)

SVR()

In [ ]:
#Making predictions
svr_pred = svr_reg.predict(X_test)
svr_pred

array([1.72930462, 2.2756762 , 0.76080943, ..., 2.05595118, 1.76671968,
       0.98554852])

Explanation:

SVR can model non-linear relationships using kernel functions, which can be helpful for datasets with complex feature-target relationships. It works well when the dataset has fewer outliers, as it is sensitive to them.

The California Housing dataset, with multiple features influencing house prices, might benefit from SVR's ability to handle non-linear patterns.


# 3. Model Evaluation and Comparison

Lets Evaluate the performance of each algorithm using the following metrics:-

Mean Squared Error (MSE) , Mean Absolute Error (MAE) , R-squared Score (R²)

In [ ]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

i)Linear regression model

In [ ]:
# predication made is stored in linear_pred
#Lets calculate evaluation metrices
#Mean squared error metric
mse_linear = mean_squared_error(y_test,linear_pred)
#Mean absolute error
mae_linear = mean_absolute_error(y_test,linear_pred)
#r2score
r2_linear = r2_score(y_test,linear_pred)
print("Linear regression Evaluation: ")
print("Mean Squared Error: ",mse_linear)
print("Mean absolute Error: ",mae_linear)
print("R2 score: ",r2_linear)

Linear regression Evaluation: 
Mean Squared Error:  0.5417517275769405
Mean absolute Error:  0.5389572480554761
R2 score:  0.6075794091011186


ii) Decision tree regression

In [ ]:
# predication made is stored in dt_pred
#Lets calculate evaluation metrices
#Mean squared error metric
mse_dt = mean_squared_error(y_test,dt_pred)
#Mean absolute error
mae_dt = mean_absolute_error(y_test,dt_pred)
#r2score
r2_dt = r2_score(y_test,dt_pred)
print("Decision Tree Regression Evaluation: ")
print("Mean Squared Error: ",mse_dt)
print("Mean absolute Error: ",mae_dt)
print("R2 score: ",r2_dt)

Decision Tree Regression Evaluation: 
Mean Squared Error:  0.5345388479502422
Mean absolute Error:  0.4672826695736434
R2 score:  0.6128040947663609


iii)Random Forest Regression


In [ ]:
# predication made is stored in rf_pred
#Lets calculate evaluation metrices
#Mean squared error metric
mse_rf = mean_squared_error(y_test,rf_pred)
#Mean absolute error
mae_rf = mean_absolute_error(y_test,rf_pred)
#r2score
r2_rf = r2_score(y_test,rf_pred)
print("Random Forest Regression Evaluation: ")
print("Mean Squared Error: ",mse_rf)
print("Mean absolute Error: ",mae_rf)
print("R2 score: ",r2_rf)

Random Forest Regression Evaluation: 
Mean Squared Error:  0.27196625912173134
Mean absolute Error:  0.3386340897286823
R2 score:  0.8029998712021628


iv)Gradient Boosting Regression

In [ ]:
# predication made is stored in gb_pred
#Lets calculate evaluation metrices
#Mean squared error metric
mse_gb = mean_squared_error(y_test,gb_pred)
#Mean absolute error
mae_gb = mean_absolute_error(y_test,gb_pred)
#r2score
r2_gb = r2_score(y_test,gb_pred)
print("Gradient Boosting Regression Evaluation: ")
print("Mean Squared Error: ",mse_gb)
print("Mean absolute Error: ",mae_gb)
print("R2 score: ",r2_gb)

Gradient Boosting Regression Evaluation: 
Mean Squared Error:  0.29886481441666796
Mean absolute Error:  0.37519795077795715
R2 score:  0.7835157672743795


v)Support Vector Regression

In [ ]:
# predication made is stored in svr_pred
#Lets calculate evaluation metrices
#Mean squared error metric
mse_svr = mean_squared_error(y_test,svr_pred)
#Mean absolute error
mae_svr = mean_absolute_error(y_test,svr_pred)
#r2score
r2_svr = r2_score(y_test,svr_pred)
print("Support Vector Regression Evaluation: ")
print("Mean Squared Error: ",mse_svr)
print("Mean absolute Error: ",mae_svr)
print("R2 score: ",r2_svr)

Support Vector Regression Evaluation: 
Mean Squared Error:  0.3652627720578998
Mean absolute Error:  0.39950275211120995
R2 score:  0.7354200724279785


In [ ]:
#Lets compare the evaluation results:

print("Linear regression Evaluation: ")
print("Mean Squared Error: ",mse_linear)
print("Mean absolute Error: ",mae_linear)
print("R2 score: ",r2_linear)

print("\nDecision Tree Regression Evaluation: ")
print("Mean Squared Error: ",mse_dt)
print("Mean absolute Error: ",mae_dt)
print("R2 score: ",r2_dt)

print("\nRandom Forest Regression Evaluation: ")
print("Mean Squared Error: ",mse_rf)
print("Mean absolute Error: ",mae_rf)
print("R2 score: ",r2_rf)

print("\nGradient Boosting Regression Evaluation: ")
print("Mean Squared Error: ",mse_gb)
print("Mean absolute Error: ",mae_gb)
print("R2 score: ",r2_gb)

print("\nSupport Vector Regression Evaluation: ")
print("Mean Squared Error: ",mse_svr)
print("Mean absolute Error: ",mae_svr)
print("R2 score: ",r2_svr)

Linear regression Evaluation: 
Mean Squared Error:  0.5417517275769405
Mean absolute Error:  0.5389572480554761
R2 score:  0.6075794091011186

Decision Tree Regression Evaluation: 
Mean Squared Error:  0.5345388479502422
Mean absolute Error:  0.4672826695736434
R2 score:  0.6128040947663609

Random Forest Regression Evaluation: 
Mean Squared Error:  0.27196625912173134
Mean absolute Error:  0.3386340897286823
R2 score:  0.8029998712021628

Gradient Boosting Regression Evaluation: 
Mean Squared Error:  0.29886481441666796
Mean absolute Error:  0.37519795077795715
R2 score:  0.7835157672743795

Support Vector Regression Evaluation: 
Mean Squared Error:  0.3652627720578998
Mean absolute Error:  0.39950275211120995
R2 score:  0.7354200724279785


Best-Performing Algorithm:

Lower MSE and MAE: These indicate the model's prediction is closer to the actual values, which generally translates to better performance. Higher R²: A higher R² value indicates that the model is better at explaining the variance in the target variable (i.e., it fits the data well).

" Here in this Project, We got Lower MSE and MAE , Higher R^2 value for Random forest Regression model, So we can conclude that Random forest model's the Best performing Algorithm. Also Gradient boosting Regression model evaluated as a good performing algorithm "

Worst-Performing Algorithm:

Higher MSE and MAE: Models with higher values of MSE and MAE are not predicting well. Lower R²: A lower R² means the model doesn't explain much of the variance in the data

" Here in this Project, We got Lower MSE and MAE , Higher R^2 value for Linear Regression mode and Decision tree model, So we can conclude that Linear regression Algorithm and DEcision tree Algorithm are both performing worst in this case. "